
spring:
  profiles:
    active: qa
---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  #spring.data.jpa.repositories.bootstrap-mode=default
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: qa
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-qa
  #spring.data.jpa.repositories.bootstrap-mode=default
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss



management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---
server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-prod
  #spring.data.jpa.repositories.bootstrap-mode=default
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
